### ISSUE TITLE
你好，支持Android 端的浏览器吗？

### ISSUE THREAD

**Issue by Sabirjan** [wangduanduan/wellclient#11]
你好，支持Android 端的浏览器吗？

**Comment by wangduanduan** [comment]
webkit内核应该都支持，主要是浏览器必须支持原生websocket。大部分用户都是用的PC端，没试过移动端。

**Comment by Sabirjan** [comment]
demo 有点复杂，无法对接本地的FS

**Comment by Sabirjan** [comment]
demo 有点复杂，无法对接本地的FS
